image: shortishly/docker-erlang

before_script:
  - git config --global url.http://gitlab.dev.sunninghill.org/shortishly.insteadOf https://github.com/shortishly

stages:
  - build

master:
  stage: build
  script:
    - make
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag $(bin/release_name):$(bin/version) $DOCKER_USERNAME/$(bin/app):$(bin/version)
    - docker tag $(bin/release_name):$(bin/version) $DOCKER_USERNAME/$(bin/app):latest
    - docker push $DOCKER_USERNAME/$(bin/app):$(bin/version)
    - docker push $DOCKER_USERNAME/$(bin/app):latest
    - docker rmi $DOCKER_USERNAME/$(bin/app):$(bin/version)
    - docker rmi $DOCKER_USERNAME/$(bin/app):latest
    - docker rmi $(bin/release_name):$(bin/version)
  only:
    - master

app:
  stage: build
  script:
    - make deps app
  only:
    - develop
